openapi: 3.1.0
info:
  title: GetLago+ API
  version: 1.0.0
paths:
  /v1/entitlement/authorize:
    post:
      tags:
        - Authorization entitlement
      summary: Authorize user action
      description: |
        Authorize publisher user action on resouces based on Amazon Verified Permissions (AVP) entitlements. Reference to [this story technical design](https://docs.google.com/document/d/1ggbf4sydK9gM4UAvSkrj5sWCrm7KZNUBttgv0IYUROM/edit?usp=sharing)
      operationId: authorizeEntitlement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - publisherId
                - actionName
                - resource
                - timestamp
              properties:
                userId:
                  type: string
                publisherId:
                  type: string
                actionName:
                  type: string
                context:
                  type: object
                resource:
                  type: object
                  required:
                    - id
                    - type  
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    type:
                      type: string
                    author:
                      type: string
                    tags:
                      type: array
                      items:
                        type: string
                    category:
                      type: string
                timestamp:
                  type: string
                  format: date-time
      responses:
        "200":
          description: Successful operation
        "401":
          description: Unauthorized
        "422":
          description: Request payload error
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
