# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscription_charge.service.proto

require 'google/protobuf'

require 'subscription_charge.dto_pb'


descriptor_data = "\n!subscription_charge.service.proto\x12\x13subscription_charge\x1a\x1dsubscription_charge.dto.proto2\xee\x05\n\x1dSubscriptionChargeGrpcService\x12\x88\x01\n\x18\x43reateSubscriptionCharge\x12\x30.subscription_charge.CreateSubscriptionChargeReq\x1a\x38.subscription_charge.SubscriptionChargeContractStatusRes\"\x00\x12\x88\x01\n\x18UpdateSubscriptionCharge\x12\x30.subscription_charge.UpdateSubscriptionChargeReq\x1a\x38.subscription_charge.SubscriptionChargeContractStatusRes\"\x00\x12\x8c\x01\n\x1a\x46inalizeSubscriptionCharge\x12\x32.subscription_charge.FinalizeSubscriptionChargeReq\x1a\x38.subscription_charge.SubscriptionChargeContractStatusRes\"\x00\x12\x9e\x01\n#GetSubscriptionChargeContractStatus\x12;.subscription_charge.GetSubscriptionChargeContractStatusReq\x1a\x38.subscription_charge.SubscriptionChargeContractStatusRes\"\x00\x12\x86\x01\n\x1bGetSubscriptionChargeStatus\x12\x33.subscription_charge.GetSubscriptionChargeStatusReq\x1a\x30.subscription_charge.SubscriptionChargeStatusRes\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module SubscriptionCharge
end
