# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscription_charge.proto

require 'google/protobuf'

require 'subscription_charge.service_pb'


descriptor_data = "\n\x19subscription_charge.proto\x12\x13subscription_charge\x1a!subscription_charge.service.protoP\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module SubscriptionCharge
end
