# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: subscription_charge.service.proto for package 'subscription_charge'

require 'grpc'
require 'subscription_charge.service_pb'

module SubscriptionCharge
  module SubscriptionChargeGrpcService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'subscription_charge.SubscriptionChargeGrpcService'

      rpc :CreateSubscriptionCharge, ::SubscriptionCharge::CreateSubscriptionChargeReq, ::SubscriptionCharge::SubscriptionChargeContractStatusRes
      rpc :UpdateSubscriptionCharge, ::SubscriptionCharge::UpdateSubscriptionChargeReq, ::SubscriptionCharge::SubscriptionChargeContractStatusRes
      rpc :FinalizeSubscriptionCharge, ::SubscriptionCharge::FinalizeSubscriptionChargeReq, ::SubscriptionCharge::SubscriptionChargeContractStatusRes
      rpc :GetSubscriptionChargeContractStatus, ::SubscriptionCharge::GetSubscriptionChargeContractStatusReq, ::SubscriptionCharge::SubscriptionChargeContractStatusRes
      rpc :GetSubscriptionChargeStatus, ::SubscriptionCharge::GetSubscriptionChargeStatusReq, ::SubscriptionCharge::SubscriptionChargeStatusRes
    end

    Stub = Service.rpc_stub_class
  end
end
