# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_token.proto

require 'google/protobuf'


descriptor_data = "\n\x10\x61uth_token.proto\x12\x04\x61uth\"\x1c\n\x0b\x41uthRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1e\n\x0c\x41uthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2:\n\x05Token\x12\x31\n\x06Verify\x12\x11.auth.AuthRequest\x1a\x12.auth.AuthResponse\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Auth
  AuthRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.AuthRequest").msgclass
  AuthResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.AuthResponse").msgclass
end
