# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: auth_token.proto for package 'auth'

require 'grpc'
require 'auth_token_pb'

module Auth
  module Token
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'auth.Token'

      rpc :Verify, ::Auth::AuthRequest, ::Auth::AuthResponse
    end

    Stub = Service.rpc_stub_class
  end
end
