# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: revenue.service.proto

require 'google/protobuf'

require 'revenue-subscription-charge.dto_pb'


descriptor_data = "\n\x15revenue.service.proto\x12\x07revenue\x1a%revenue-subscription-charge.dto.proto2\xe7\x04\n\x12RevenueGrpcService\x12p\n\x18\x43reateSubscriptionCharge\x12$.revenue.CreateSubscriptionChargeReq\x1a,.revenue.SubscriptionChargeContractStatusRes\"\x00\x12p\n\x18UpdateSubscriptionCharge\x12$.revenue.UpdateSubscriptionChargeReq\x1a,.revenue.SubscriptionChargeContractStatusRes\"\x00\x12t\n\x1a\x46inalizeSubscriptionCharge\x12&.revenue.FinalizeSubscriptionChargeReq\x1a,.revenue.SubscriptionChargeContractStatusRes\"\x00\x12\x86\x01\n#GetSubscriptionChargeContractStatus\x12/.revenue.GetSubscriptionChargeContractStatusReq\x1a,.revenue.SubscriptionChargeContractStatusRes\"\x00\x12n\n\x1bGetSubscriptionChargeStatus\x12\'.revenue.GetSubscriptionChargeStatusReq\x1a$.revenue.SubscriptionChargeStatusRes\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Revenue
end
