# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: revenue.proto

require 'google/protobuf'

require 'revenue.service_pb'


descriptor_data = "\n\rrevenue.proto\x12\x07revenue\x1a\x15revenue.service.protoP\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Revenue
end
